version: '3.9'

services:
  fastapi-app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"


