
services:
  - type: web
    name: insurance-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn insurance_app_main\ 1:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000